### PR TITLE
test_manager: Fix exception on job timeout

### LINKED ISSUE #254: Crash on master with timeout (AttributeError: 'TestManager' object has no attribute 'timeout_count')
First, thanks for cvise, and also thanks for the recent improvements!

On master with https://github.com/marxin/cvise/pull/253 applied on top, I see the following after a while of runtime:
```
$ TMPDIR=~/tmp cvise test.sh widen_mul_test.cxx --print-diff --timeout 480
[...]
01:35:22 INFO (81.6%, 106168 bytes, 2710 lines)
Traceback (most recent call last):
  File "/usr/bin/cvise", line 541, in <module>
    main()
    ~~~~^^
  File "/usr/bin/cvise", line 355, in main
    do_reduce(args)
    ~~~~~~~~~^^^^^^
  File "/usr/bin/cvise", line 473, in do_reduce
    reducer.reduce(pass_group, skip_initial=args.skip_initial_passes)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cvise/cvise.py", line 204, in reduce
    self._run_pass_category(passes, category)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/share/cvise/cvise.py", line 222, in _run_pass_category
    met_stopping_threshold = self._run_passes(passes, category.interleaving, check_threshold=True)
  File "/usr/share/cvise/cvise.py", line 245, in _run_passes
    self.test_manager.run_passes([p], interleaving)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cvise/utils/testing.py", line 711, in run_passes
    self.run_parallel_tests()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/share/cvise/utils/testing.py", line 634, in run_parallel_tests
    if self.process_done_futures():
       ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/share/cvise/utils/testing.py", line 519, in process_done_futures
    self.timeout_count += 1
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'TestManager' object has no attribute 'timeout_count'
```

Let me know if I need to give more useful information.

### PR DESCRIPTION
**Pull request by emaxx-google**
Fix the regression introduced in #199 - a fatal exception when any transformation job times out.

This fixes #254. This is a quick fix - the long-term idea was to account for timeouts separately, for each individual pass even when multiple passes are running in interleaving mode; this was lost in some merge-rebase conflict, so we'll redo it properly in a follow-up.

### CODE REVIEW

**Review by VitaNuo — APPROVED** [review]
Thanks!

**Comment by emaxx-google** [comment]
Thank you for all reviews!
